language: nix

cache:
  directories:
  - "/nix"

script:
- |
  nix-env -f "<nixpkgs>" -iA haskellPackages.cabal-install
  nix-shell -E 'with import <nixpkgs> {}; haskell.packages.ghc821.ghcWithPackages (pkgs: [ ])' --command 'cabal install deps/trivial/ . --depdencies-only && cabal configure --enable-tests && cabal install deps/trivial/ . && cabal test'
