name: middle-out
version: '0.1.0.0'
author: S. M. Hickman
maintainer: sean@grump.ly
license: BSD3
dependencies:
- base >=4.8
- containers
library:
  source-dirs:
    - src
  exposed-modules:
    - Data.MiddleOut
